---
- name: Deploy Gateway
  hosts: gateway
  tasks:
    - name: Copy sa-registry.secret.json
      ansible.builtin.copy:
        src: ../../data/sa-registry.secret.json
        dest: /home/dima-batalov/sa-registry.secret.json
    - name: Login registry
      shell: cat /home/dima-batalov/sa-registry.secret.json | docker login --username json_key --password-stdin cr.yandex
    - name: Pull default Docker image
      community.docker.docker_image:
        name: "cr.yandex/crp38865vs41akamblti/backend:latest"
        source: pull
    - name: Stop all containers
      shell: docker ps | awk '{print $1}' | tail -n +1 | xargs -I{} docker container stop {}
      ignore_errors: true
    - name: Serve
      community.docker.docker_container:
        name: "backend"
        image: "cr.yandex/crp38865vs41akamblti/backend:latest"
        detach: true
        env:
          - name: MODEL_URL
            value: 10.0.10.1
        published_ports: 
          - 127.0.0.1:8080:80/tcp
        restart_policy: always
